/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#302f39",
        "secondary": "#0058be",
        "primary-fixed-dim": "#c3c0ff",
        "on-secondary-fixed": "#001a42",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#f5f2ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#67f4b7",
        "on-primary-fixed-variant": "#3323cc",
        "surface-container-high": "#eae6f4",
        "on-tertiary-fixed": "#002113",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#dcd8e5",
        "tertiary-container": "#006e4b",
        "secondary-fixed-dim": "#adc6ff",
        "secondary-fixed": "#d8e2ff",
        "on-surface-variant": "#464555",
        "secondary-container": "#2170e4",
        "on-secondary-container": "#fefcff",
        "outline": "#777587",
        "inverse-primary": "#c3c0ff",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fcf8ff",
        "on-surface": "#1b1b24",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#fcf8ff",
        "on-primary-container": "#dad7ff",
        "tertiary": "#005338",
        "on-error": "#ffffff",
        "surface-tint": "#4d44e3",
        "outline-variant": "#c7c4d8",
        "on-primary-fixed": "#0f0069",
        "surface-variant": "#e4e1ee",
        "primary": "#3525cd",
        "surface-container": "#f0ecf9",
        "surface-container-lowest": "#ffffff",
        "surface": "#fcf8ff",
        "primary-container": "#4f46e5",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#e4e1ee",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-background": "#1b1b24",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f3effc",
        "on-secondary-fixed-variant": "#004395"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "gutter": "24px",
        "lg": "40px",
        "sm": "16px",
        "xl": "64px",
        "xs": "8px",
        "md": "24px",
        "base": "4px"
      },
      fontFamily: {
        "headline-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "caption": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "caption": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}